https://github.com/sharebook-kr/pykrx

In [2]:
from pykrx import stock
# 티커리스트 조회
# input : 일자(미 입력 시 최근 영업일 DEFAULT)
#   - market: KOSPI(DEFAULT), KOSDAQ, KONEX, ALL
tickers = stock.get_market_ticker_list("20210830", market='KOSDAQ')
print(tickers)

['060310', '054620', '265520', '211270', '013720', '035760', '051500', '058820', '023460', '056730', '056000', '065770', '083660', '367340', '367360', '068790', '241520', '245620', '037370', '079190', '050120', '130500', '900290', '083450', '045890', '227100', '297890', '078150', '195940', '036640', '335870', '351340', '351320', '373200', '095340', '099520', '950170', '067290', '035900', '024840', '024120', '021320', '036670', '044180', '151860', '046440', '035600', '226360', '111870', '060720', '122450', '052900', '058400', '114450', '060370', '108320', '160550', '053290', '104200', '060250', '030190', '078590', '024940', '218410', '327260', '091340', '019550', '950110', '046140', '036120', '099220', '036540', '255220', '040610', '049470', '184230', '016250', '337450', '340350', '036490', '048550', '063440', '950180', '289080', '089230', '161570', '192410', '032540', '048770', '246690', '317240', '038340', '073570', '057030', '040300', '051390', '052220', '079940', '078890', '036620', '217730', '114190', '094480', '063080', '039240', '053950', '223310', '011040', '024910', '198440', '049720', '014570', '348150', '098460', '035290', '038530', '900280', '215000', '121440', '014200', '026910', '090150', '355150', '331520', '053270', '066620', '043650', '006050', '060480', '078130', '307750', '204020', '186230', '900070', '204620', '019660', '053260', '036190', '049080', '035460', '308100', '187790', '286750', '151910', '121600', '247660', '039860', '091970', '051490', '190510', '242040', '089600', '293580', '138610', '130580', '036800', '267320', '111710', '091590', '168330', '094860', '253590', '212560', '095660', '042420', '950220', '311390', '085910', '092730', '290660', '306620', '153460', '007390', '033640', '330860', '089140', '065170', '137940', '348210', '041140', '217270', '225570', '104620', '194700', '285490', '278650', '144510', '031390', '142280', '234690', '065560', '054050', '069140', '040160', '126870', '060260', '012340', '214870', '270870', '144960', '085670', '119860', '064260', '093640', '340360', '039560', '032190', '068240', '020400', '008830', '048470', '004780', '017650', '007720', '317850', '290670', '078140', '036480', '025440', '027830', '104040', '332290', '336570', '369370', '020180', '045390', '108380', '006580', '007680', '048910', '005710', '290380', '290120', '120240', '003310', '078600', '096350', '140520', '131220', '010170', '060900', '054670', '023910', '021040', '021045', '067080', '298540', '299170', '213420', '317330', '077360', '090410', '263600', '194480', '263800', '206560', '261200', '067990', '006620', '100130', '005160', '075970', '086450', '099410', '033500', '025950', '088130', '041930', '060380', '079960', '228340', '088910', '094170', '013120', '109860', '032960', '023790', '005290', '025900', '073190', '030350', '203650', '223250', '060570', '217620', '187870', '066670', '110990', '263690', '214680', '263720', '109740', '033430', '131030', '196490', '066900', '127120', '092070', '134580', '039840', '104460', '079810', '113810', '043360', '197140', '106520', '068930', '033130', '105740', '263020', '290550', '187220', '131180', '315640', '317120', '042510', '232680', '300120', '171120', '069540', '347700', '214260', '171010', '084650', '217500', '141080', '060300', '038390', '294140', '228670', '228850', '281740', '277810', '215100', '090360', '108490', '900260', '067730', '071280', '038060', '085370', '08537M', '060240', '058470', '039980', '019570', '016100', '012700', '302550', '029480', '277070', '042500', '219420', '195500', '222810', '305090', '098120', '147760', '038290', '220630', '267980', '005990', '127160', '093520', '141070', '377030', '100590', '067280', '072870', '215200', '133750', '235980', '041920', '014100', '054180', '086900', '078160', '065650', '021880', '140410', '241770', '059210', '058110', '096640', '257370', '080420', '080160', '100030', '087260', '101330', '012860', '348030', '250060', '033200', '118990', '006920', '001810', '279600', '095500', '218150', '353490', '328380', '100790', '049950', '213090', '207760', '059090', '214610', '201490', '950190', '214180', '206640', '018700', '035620', '064520', '053030', '301300', '064550', '314930', '208710', '142760', '086820', '038460', '086040', '032980', '308080', '043150', '323990', '267790', '046310', '066410', '206400', '019010', '177350', '299910', '225530', '250000', '006910', '226340', '014470', '008470', '338220', '100120', '337930', '099390', '064480', '288330', '251630', '018290', '044480', '033560', '126340', '121800', '148140', '082800', '318410', '200780', '141000', '090460', '083650', '086670', '335890', '138580', '082920', '054220', '042370', '032850', '238200', '093190', '065450', '072950', '143240', '100090', '122350', '014970', '018310', '053700', '009620', '023600', '380320', '377630', '009300', '225190', '361670', '054540', '065570', '032280', '002290', '037460', '032750', '054090', '000250', '024950', '038500', '017480', '046390', '027580', '038540', '307870', '329560', '101000', '091580', '263810', '089980', '042940', '042600', '252990', '263540', '294630', '038070', '006730', '079650', '100660', '019770', '043710', '092190', '046890', '063170', '027040', '018680', '093920', '189860', '178320', '122690', '140070', '011370', '065710', '035890', '357550', '003100', '123420', '171090', '086710', '014620', '037350', '081580', '045300', '015750', '080470', '043260', '148150', '053060', '017510', '011560', '052190', '100700', '234100', '024830', '258830', '036630', '039310', '067770', '053450', '234340', '252500', '347000', '331920', '049180', '299660', '268600', '108860', '208370', '068760', '091990', '290690', '053110', '950200', '032680', '032685', '258790', '066910', '043100', '154040', '035610', '357780', '036830', '304100', '086980', '050960', '084180', '253840', '058530', '236200', '317770', '094840', '192440', '099440', '033790', '131100', '159910', '115570', '253450', '204630', '013810', '039670', '049830', '020710', '033170', '048870', '025320', '269620', '131090', '139050', '290520', '001000', '025870', '215600', '065350', '002800', '323280', '344050', '017000', '012790', '138070', '226330', '333050', '366330', '056700', '187270', '243840', '222800', '036710', '160980', '356890', '217330', '010280', '208640', '222420', '037760', '136510', '099320', '049960', '050890', '066790', '222080', '352480', '264660', '352700', '297090', '115530', '225330', '115480', '189330', '096530', '900120', '101240', '060590', '260930', '013990', '123860', '025980', '050320', '058220', '125210', '357580', '052710', '074430', '092040', '083930', '149950', '036010', '050860', '246720', '067390', '127710', '154030', '227610', '143160', '054800', '332370', '339950', '099190', '289010', '214430', '040910', '068940', '052860', '069920', '038880', '307180', '101390', '078860', '114810', '031310', '185490', '059100', '262840', '175250', '052460', '119830', '052770', '124500', '084850', '027360', '032080', '013310', '059120', '158430', '067160', '001540', '053800', '065660', '297570', '260660', '131370', '140670', '096610', '061040', '148250', '347860', '196170', '123750', '085810', '117670', '291650', '293780', '196300', '310200', '900100', '205500', '052790', '290740', '238090', '092600', '129890', '174900', '255440', '030960', '102120', '238120', '019990', '270660', '038680', '217480', '121890', '097780', '042110', '298060', '065420', '103230', '101490', '095910', '275630', '031330', '060540', '056190', '080000', '214310', '041510', '007820', '109610', '306040', '080440', '096630', '069510', '041910', '234300', '039440', '098660', '052020', '237690', '050760', '288620', '317830', '058610', '043340', '187660', '054630', '200710', '096690', '298380', '195990', '003800', '088800', '241840', '039230', '312610', '072990', '176440', '028300', '067630', '047920', '043220', '239610', '353070', '353060', '044780', '357230', '071670', '045660', '224110', '230980', '021080', '089530', '200470', '262260', '109960', '089970', '230240', '064510', '230360', '038870', '128540', '086520', '247540', '383310', '038110', '073540', '064850', '064090', '036810', '173940', '083500', '054940', '950130', '205100', '070300', '092870', '317870', '067570', '236810', '333620', '101400', '217820', '031860', '310840', '359090', '365590', '265740', '354200', '208860', '183490', '182400', '069410', '227950', '291230', '198080', '048830', '096870', '376190', '061970', '138690', '290650', '066970', '156100', '073110', '083310', '037950', '170920', '058630', '058970', '019590', '169330', '179290', '009780', '123040', '323230', '032790', '033160', '347890', '033310', '259630', '065150', '115960', '090740', '060850', '007530', '143540', '036560', '265560', '036000', '250930', '053280', '122640', '900300', '045060', '080520', '039830', '322310', '046120', '014940', '065500', '010470', '352910', '053980', '052420', '241790', '039200', '226400', '031510', '048260', '138080', '080580', '067170', '173130', '049480', '309930', '244460', '226950', '057540', '082210', '109080', '153710', '321820', '122990', '232140', '065530', '067900', '155650', '251370', '066430', '193250', '273060', '019210', '122870', '332570', '079000', '032820', '041190', '115440', '046970', '082850', '215360', '072470', '073560', '153490', '037400', '101170', '066590', '103840', '046940', '215380', '065680', '018620', '307280', '053080', '032940', '240810', '074600', '104830', '014190', '131390', '030530', '012620', '376980', '008370', '008290', '101160', '095270', '065950', '076080', '196700', '069080', '053580', '071460', '044340', '330350', '348350', '112040', '101730', '065370', '038620', '299900', '036090', '136540', '320000', '097800', '192390', '313760', '900340', '036200', '018000', '203450', '011320', '086390', '241690', '142210', '048430', '206650', '089850', '032620', '264450', '078070', '024800', '054930', '069330', '049520', '313750', '336060', '367460', '367480', '056090', '263770', '340930', '023410', '056080', '321260', '331380', '373340', '084370', '178780', '179900', '263050', '191410', '072770', '039020', '060230', '067920', '044960', '303530', '302430', '073490', '086250', '215790', '246960', '088390', '272290', '053350', '258610', '041520', '264850', '054210', '164060', '065440', '115610', '349720', '323210', '078020', '131400', '351330', '080010', '086890', '047560', '900110', '067010', '101360', '102710', '066980', '063760', '087730', '123570', '083470', '095190', '091120', '039030', '294090', '088290', '181340', '353810', '099750', '035810', '160600', '092130', '096040', '134060', '001840', '024810', '041830', '352940', '079950', '277410', '060150', '033230', '037330', '083640', '216050', '049070', '119610', '017250', '035080', '051370', '064290', '189300', '150840', '048530', '175140', '115310', '039290', '071200', '016670', '101930', '333430', '068330', '058450', '019540', '094820', '950140', '049550', '254120', '221610', '219550', '043910', '234920', '289220', '174880', '049630', '110020', '208140', '022220', '040420', '045510', '217190', '095700', '072520', '122310', '361390', '187420', '225220', '123330', '159580', '147830', '033100', '079370', '054950', '090470', '287410', '137950', '033320', '204270', '026040', '126880', '322510', '033050', '094970', '058420', '089790', '052670', '199820', '023440', '038010', '276730', '080220', '216080', '229000', '082270', '064800', '041590', '044060', '034940', '067000', '033340', '036930', '239340', '051980', '072020', '000440', '078650', '228760', '314130', '043610', '263860', '303030', '036180', '208350', '114570', '051160', '053050', '119850', '270520', '065060', '204840', '111820', '115450', '219750', '018120', '109820', '086060', '036890', '363250', '007370', '085660', '158310', '094850', '004650', '311690', '278280', '096240', '066360', '047820', '052300', '094360', '016920', '284620', '293490', '042000', '317530', '071850', '180400', '050110', '900310', '078340', '307930', '263700', '214370', '221980', '317030', '323940', '330990', '342550', '192250', '115500', '089150', '025880', '093320', '073010', '105330', '272110', '039420', '083550', '032500', '225430', '036030', '064820', '347140', '256940', '024880', '042040', '054410', '274090', '217600', '089010', '220260', '052400', '033110', '046070', '047770', '078940', '080530', '224060', '104540', '027050', '290510', '190650', '101670', '123410', '036690', '049430', '183300', '041960', '089890', '009730', '082660', '222040', '241710', '069110', '166480', '045970', '196450', '029960', '102940', '950160', '033290', '056360', '282880', '121850', '015710', '052330', '322780', '126600', '200130', '294570', '317690', '365270', '060280', '040350', '051780', '115180', '043090', '182360', '066310', '016600', '043590', '114120', '110790', '900250', '083790', '045520', '036170', '214150', '352770', '237880', '139670', '054780', '219130', '065130', '023160', '053620', '044490', '124560', '191420', '073640', '182690', '066700', '095610', '131970', '089030', '054450', '091440', '200230', '215480', '051360', '045340', '108230', '079970', '105550', '026150', '322180', '117730', '033830', '057680', '064760', '246710', '340570', '277880', '131290', '356860', '062860', '321550', '104480', '081150', '130740', '084730', '046210', '034230', '033540', '043200', '214450', '208340', '177830', '037070', '150900', '037030', '047310', '170790', '049120', '038950', '106240', '131760', '065690', '140860', '091700', '032800', '318010', '027710', '225590', '054300', '068050', '222110', '263750', '251970', '087010', '119500', '022100', '009520', '189690', '318020', '256630', '141020', '041020', '114630', '123010', '290720', '005670', '094940', '007330', '093380', '023900', '214270', '220100', '035200', '334970', '203690', '053610', '335810', '053160', '367000', '075130', '237820', '023770', '300080', '032580', '051380', '241820', '237750', '024850', '319660', '031980', '002230', '057880', '043370', '239890', '347740', '137400', '128660', '006140', '304840', '062970', '087600', '161580', '347770', '163730', '332710', '341160', '343510', '363260', '299030', '067310', '372290', '166090', '136480', '003380', '149980', '013030', '126700', '106080', '340120', '377400', '221840', '106190', '066130', '368770', '004590', '039340', '034950', '222980', '318000', '256840', '025550', '017890', '080720', '063570', '041460', '101680', '039740', '053300', '025770', '310870', '023760', '054040', '050540', '021650', '053590', '032300', '037230', '030520', '052600', '256150', '092460', '047080', '070590', '226440', '042520', '078350', '045100', '046110', '024740', '005860', '123840', '007770', '079170', '086960', '054920', '002680', '066110', '317320', '340440', '386580', '034810', '076610', '059270', '220180', '900270', '084990', '170030', '319400', '048410', '052260', '016790', '041440', '039010', '090850', '092300', '053660', '138360', '011080', '060560', '064240', '039610', '126640', '061250', '097870', '050090', '290270', '353190', '090710', '205470', '115160', '028080', '032860', '200670', '065510', '215090', '243070', '084110', '263920', '145020', '024060', '010240', '189980', '037440', '238490']

In [166]:
# 종목이름 조회
# input : ticker
for ticker in stock.get_market_ticker_list():
  name = stock.get_market_ticker_name(ticker)
  print(name)

AJ네트웍스
AK홀딩스
BGF
BGF리테일
BNK금융지주
BYC
BYC우
CJ
CJ CGV
CJ4우(전환)
CJ대한통운
CJ씨푸드
CJ씨푸드1우
CJ우
CJ제일제당
CJ제일제당 우
CS홀딩스
DB
DB금융투자
DB손해보험
DB하이텍
DB하이텍1우
DGB금융지주
DI동일
DL
DL건설
DL우
DL이앤씨
DL이앤씨우
DRB동일
DSR
DSR제강
E1
ESR켄달스퀘어리츠
F&F
F&F홀딩스
GKL
GS
GS건설
GS글로벌
GS리테일
GS우
HDC
HDC아이콘트롤스
HDC현대EP
HDC현대산업개발
HMM
HSD엔진
IHQ
JB금융지주
JW생명과학
JW중외제약
JW중외제약2우B
JW중외제약우
JW홀딩스
KB금융
KCC
KCC글라스
KCTC
KC그린홀딩스
KC코트렐
KEC
KG동부제철
KG동부제철우
KG케미칼
KH 필룩스
KISCO홀딩스
KPX케미칼
KPX홀딩스
KR모터스
KSS해운
KT
KT&G
KTB투자증권
KTcs
KTis
LF
LG
LG디스플레이
LG생활건강
LG생활건강우
LG우
LG유플러스
LG이노텍
LG전자
LG전자우
LG헬로비전
LG화학
LG화학우
LIG넥스원
LS
LS ELECTRIC
LS네트웍스
LS전선아시아
LX인터내셔널
LX하우시스
LX하우시스우
LX홀딩스
LX홀딩스1우
MH에탄올
NAVER
NHN
NH투자증권
NH투자증권우
NH프라임리츠
NICE
NI스틸
NPC
NPC우
OCI
PI첨단소재
POSCO
S-Oil
S-Oil우
SBS
SBS미디어홀딩스
SGC에너지
SG글로벌
SG세계물산
SHD
SH에너지화학
SIMPAC
SJM
SJM홀딩스
SK
SKC
SK가스
SK네트웍스
SK네트웍스우
SK디스커버리
SK디스커버리우
SK디앤디
SK렌터카
SK바이오사이언스
SK바이오팜
SK아이이테크놀로지
SK우
SK이노베이션
SK이노베이션우
SK증권
SK증권우
SK케미칼
SK케미칼우
SK텔레콤
SK하이닉스
SNT모티브
SNT에너지
SNT중공업
SNT홀딩스
SPC삼립
STX
STX엔진
STX중공업
SUN&L
TBH글로벌
TCC스틸
TYM
WISCOM
YG PLUS
가온전선
강남제비스코
강원랜드
갤럭시아에스엠
경농
경동나비엔
경동도시가스
경동인베스트
경방
경보제약
경인양행
경인전자
계룡건설
계양전기
계양전기우
고려산업
고려아연
고려제강
광동제약
광명전기
광전자
광주신세계
교보증권
교촌에프앤비
국도화학
국동
국보
국제약품
그린케미칼
극동유화
금강공업
금강공업우
금비
금양
금호건설
금호건설우
금호석유
금호석유우
금호에이치티
금호전기
금호타이어
기신정기
기아
기업은행
까뮤이앤씨
깨끗한나라
깨끗한나라우
남광토건
남선알미늄
남선알미우
남성
남양유업
남양유업우
남해화학
넥센
넥센우
넥센타이어
넥센타이어1우B
넥스트사이언스
넷마블
노루페인트
노루페인트우
노루홀딩스
노루홀딩스우
녹십자
녹십자홀딩스
녹십자홀딩스2우
농심
농심홀딩스
다스코
다우기술
다이나믹디자인
대교
대교우B
대구백화점
대덕
대덕1우
대덕전자
대덕전자1우
대동
대동전자
대림B&Co
대림통상
대상
대상우
대상홀딩스
대상홀딩스우
대성산업
대성에너지
대성홀딩스
대신증권
대신증권2우B
대신증권우
대양금속
대영포장
대우건설
대우부품
대우조선해양
대웅
대웅제약
대원강업
대원전선
대원전선우
대원제약
대원화성
대유에이텍
대유플러스
대창
대창단조
대한방직
대한유화
대한전선
대한제강
대한제당
대한제당우
대한제분
대한항공
대한항공우
대한해운
대한화섬
대현
대호에이엘
더블유게임즈
더존비즈온
덕성
덕성우
덕양산업
덴티움
도화엔지니어링
동국제강
동남합성
동방
동방아그로
동부건설
동부건설우
동서
동성제약
동성케미컬
동아쏘시오홀딩스
동아에스티
동아지질
동아타이어
동양
동양2우B
동양3우B
동양고속
동양생명
동양우
동양철관
동양피스톤
동원F&B
동원금속
동원산업
동원수산
동원시스템즈
동원시스템즈우
동일고무벨트
동일산업
동일제강
동화약품
두산
두산2우B
두산밥캣
두산우
두산인프라코어
두산중공업
두산퓨얼셀
두산퓨얼셀1우
두산퓨얼셀2우B
두올
드림텍
디씨엠
디아이
디아이씨
디앤디플랫폼리츠
디와이
디와이파워
디티알오토모티브
디피씨
락앤락
롯데관광개발
롯데렌탈
롯데리츠
롯데손해보험
롯데쇼핑
롯데정밀화학
롯데정보통신
롯데제과
롯데지주
롯데지주우
롯데칠성
롯데칠성우
롯데케미칼
롯데푸드
롯데하이마트
마니커
만도
만호제강
맥쿼리인프라
맵스리얼티1
메리츠금융지주
메리츠증권
메리츠화재
메타랩스
명문제약
명신산업
모나리자
모나미
모두투어리츠
모토닉
무림P&P
무림페이퍼
무학
문배철강
미래산업
미래아이앤지
미래에셋맵스리츠
미래에셋생명
미래에셋증권
미래에셋증권2우B
미래에셋증권우
미원상사
미원에스씨
미원홀딩스
미원화학
미창석유
바다로19호
방림
백광산업
백산
범양건영
베트남개발1
벽산
보락
보령제약
보해양조
부광약품
부국증권
부국증권우
부국철강
부산가스
부산산업
부산주공
비비안
비상교육
비케이탑스
빙그레
사조대림
사조동아원
사조산업
사조씨푸드
사조오양
삼부토건
삼성SDI
삼성SDI우
삼성공조
삼성물산
삼성물산우B
삼성바이오로직스
삼성생명
삼성에스디에스
삼성엔지니어링
삼성전기
삼성전기우
삼성전자
삼성전자우
삼성제약
삼성중공업
삼성중공우
삼성증권
삼성출판사
삼성카드
삼성화재
삼성화재우
삼아알미늄
삼양사
삼양사우
삼양식품
삼양통상
삼양패키징
삼양홀딩스
삼양홀딩스우
삼영무역
삼영전자
삼영화학
삼원강재
삼익THK
삼익악기
삼일씨엔에스
삼일제약
삼정펄프
삼진제약
삼천리
삼호개발
삼화왕관
삼화전기
삼화전자
삼화콘덴서
삼화페인트
상상인증권
상신브레이크
새론오토모티브
샘표
샘표식품
서연
서연이화
서울가스
서울식품
서울식품우
서원
서흥
선도전기
선진
성문전자
성문전자우
성보화학
성신양회
성신양회우
성안
성창기업지주
세기상사
세방
세방우
세방전지
세아베스틸
세아제강
세아제강지주
세아특수강
세아홀딩스
세우글로벌
세원이앤씨
세원정공
세이브존I&C
세종공업
세진중공업
세하
센트랄모텍
센트럴인사이트
셀트리온
솔루스첨단소재
솔루스첨단소재1우
솔루스첨단소재2우B
솔루엠
송원산업
수산중공업
스카이라이프
시디즈
신대양제지
신도리코
신라교역
신성이엔지
신성통상
신세계
신세계 I&C
신세계건설
신세계인터내셔날
신세계푸드
신송홀딩스
신영와코루
신영증권
신영증권우
신원
신원우
신일전자
신풍제약
신풍제약우
신풍제지
신한알파리츠
신한지주
신흥
쌍방울
쌍용C&E
쌍용차
써니전자
쎌마테라퓨틱스
씨아이테크
씨에스윈드
아남전자
아모레G
아모레G3우(전환)
아모레G우
아모레퍼시픽
아모레퍼시픽우
아세아
아세아시멘트
아세아제지
아센디오
아시아나IDT
아시아나항공
아이마켓코리아
아이에스동서
아주스틸
알루코
애경산업
애경유화
에넥스
에스디바이오센서
에스엘
에스원
에쓰씨엔지니어링
에어부산
에이리츠
에이블씨엔씨
에이엔피
에이프로젠 MED
에이프로젠제약
에이플러스에셋
엔씨소프트
엔에스쇼핑
엔에이치스팩19호
엔케이
엔케이물산
엘브이엠씨홀딩스
엠씨넥스
영보화학
영원무역
영원무역홀딩스
영진약품
영풍
영풍제지
영화금속
영흥
예스코홀딩스
오뚜기
오리엔트바이오
오리온
오리온홀딩스
와이투솔루션
용평리조트
우리금융지주
우리들휴브레인
우리종금
우성사료
우신시스템
우진
우진아이엔에스
우진플라임
웅진
웅진씽크빅
원림
웰바이오텍
윌비스
유나이티드제약
유니드
유니온
유니온머티리얼
유니켐
유니퀘스트
유성기업
유수홀딩스
유안타증권
유안타증권우
유엔젤
유유제약
유유제약1우
유유제약2우B
유진투자증권
유한양행
유한양행우
유화증권
유화증권우
율촌화학
이건산업
이구산업
이노션
이리츠코크렙
이마트
이수페타시스
이수화학
이스타코
이아이디
이엔플러스
이연제약
이월드
이지스레지던스리츠
이지스밸류리츠
이화산업
인디에프
인바이오젠
인스코비
인지컨트롤스
인천도시가스
인터지스
인팩
일동제약
일동홀딩스
일성건설
일성신약
일신방직
일신석재
일양약품
일양약품우
일정실업
일진다이아
일진디스플
일진머티리얼즈
일진전기
Empty DataFrame
Columns: []
Index: []
일진홀딩스
잇츠한불
자이에스앤디
자화전자
전방
제이알글로벌리츠
제이에스코퍼레이션
제이준코스메틱
제이콘텐트리
제일기획
제일약품
제일연마
제일파마홀딩스
제주은행
제주항공
조광페인트
조광피혁
조비
조선내화
조선선재
조일알미늄
조흥
종근당
종근당바이오
종근당홀딩스
주연테크
지누스
지엠비코리아
지역난방공사
지코
지투알
진도
진양산업
진양폴리
진양홀딩스
진양화학
진에어
진원생명과학
진흥기업
진흥기업2우B
진흥기업우B
참엔지니어링
천일고속
체시스
카카오
카카오뱅크
카프로
컨버즈
케이비아이동국실업
케이씨
케이씨텍
케이탑리츠
코람코에너지리츠
코리아써우
코리아써키트
코리아써키트2우B
코리안리
코스맥스
코스맥스비티아이
코스모신소재
코스모화학
코아스
코오롱
코오롱글로벌
코오롱글로벌우
코오롱머티리얼
코오롱우
코오롱인더
코오롱인더우
코오롱플라스틱
코웨이
콤텍시스템
쿠쿠홀딩스
쿠쿠홈시스
큐로
크라운제과
크라운제과우
크라운해태홀딩스
크라운해태홀딩스우
크래프톤
키다리스튜디오
키움증권
태경비케이
태경산업
태경케미컬
태광산업
태림포장
태양금속
태양금속우
태영건설
태영건설우
태원물산
태평양물산
테이팩스
텔코웨어
토니모리
티에이치엔
티와이홀딩스
티와이홀딩스우
티웨이항공
티웨이홀딩스
파미셀
팜스코
팜젠사이언스
팬오션
퍼스텍
퍼시스
페이퍼코리아
평화산업
평화홀딩스
포스코강판
포스코인터내셔널
포스코케미칼
폴루스바이오팜
풀무원
풍산
풍산홀딩스
프레스티지바이오파마
하나금융지주
하나제약
하나투어
하이골드12호
하이골드3호
하이브
하이스틸
하이트론
하이트진로
하이트진로2우B
하이트진로홀딩스
하이트진로홀딩스우
한국ANKOR유전
한국가스공사
한국공항
한국금융지주
한국금융지주우
한국내화
한국단자
한국석유
한국수출포장
한국쉘석유
한국앤컴퍼니
한국자산신탁
한국전력
한국전자홀딩스
한국조선해양
한국종합기술
한국주강
한국주철관
한국철강
한국카본
한국콜마
한국콜마홀딩스
한국타이어앤테크놀로지
한국토지신탁
한국특강
한국패러랠
한국프랜지
한국항공우주
한국화장품
한국화장품제조
한농화성
한독
한라
한라홀딩스
한미글로벌
한미반도체
한미사이언스
한미약품
한샘
한섬
한성기업
한세실업
한세엠케이
한세예스24홀딩스
한솔PNS
한솔로지스틱스
한솔제지
한솔케미칼
한솔테크닉스
한솔홀딩스
한솔홈데코
한신공영
한신기계
한양증권
한양증권우
한온시스템
한올바이오파마
한익스프레스
한일시멘트
한일철강
한일현대시멘트
한일홀딩스
한전KPS
한전기술
한전산업
한진
한진중공업
한진중공업홀딩스
한진칼
한진칼우
한창
한창제지
한컴라이프케어
한화
한화3우B
한화생명
한화손해보험
한화솔루션
한화솔루션우
한화시스템
한화에어로스페이스
한화우
한화투자증권
한화투자증권우
해성디에스
해태제과식품
핸즈코퍼레이션
현대건설
현대건설기계
현대건설우
현대그린푸드
현대글로비스
현대로템
현대리바트
현대모비스
현대미포조선
현대백화점
현대비앤지스틸
현대비앤지스틸우
현대약품
현대에너지솔루션
현대엘리베이
현대오토에버
현대위아
현대일렉트릭
현대제철
현대중공업지주
현대차
현대차2우B
현대차3우B
현대차우
현대차증권
현대코퍼레이션
현대코퍼레이션홀딩스
현대퓨처넷
현대해상
현대홈쇼핑
형지엘리트
혜인
호전실업
호텔신라
호텔신라우
화성산업
화승알앤에이
화승엔터프라이즈
화승인더
화승코퍼레이션
화신
화인베스틸
화천기계
화천기공
환인제약
황금에스티
효성
효성ITX
효성중공업
효성첨단소재
효성티앤씨
효성화학
후성
휠라홀딩스
휴니드
휴비스
휴스틸
휴켐스
흥국화재
흥국화재2우B
흥국화재우
흥아해운

In [15]:
# 일자별 OHLCV 조회
# input : 시작일/종료일/티커/(Optional)(d/m/y)
df = stock.get_market_ohlcv_by_date("20210827", "20210830", "005930")
df.head(3)

               시가     고가     저가     종가       거래량
날짜
2021-08-27  74300  75000  73800  74300  15172748
2021-08-30  75400  75500  74200  74600  12686999

In [55]:
# 전체 종목 시세 조회
# input : 날짜
#   - market: KOSPI(DEFAULT), KOSDAQ, KONEX, ALL
df = stock.get_market_ohlcv_by_ticker("20210830")
print(df.head(3))

           시가     고가     저가     종가     거래량        거래대금   등락률
티커
095570   5850   5970   5770   5920   68587   399761400  2.07
006840  26350  27400  26100  27300   56037  1499906350  3.80
027410   6320   6410   6300   6360  232110  1477499330  2.09

935

In [ ]:
# 종목별 DIV/BPS/PER/EPS 조회
# input : 날짜
#   - market: KOSPI(DEFAULT), KOSDAQ, KONEX, ALL
df = stock.get_market_fundamental_by_ticker("20210108")
df

In [ ]:
# 일자별 DIV/BPS/PER/EPS 조회
# input : 시작날짜, 종료날짜, 종목
#  - freq: d/m/y
df = stock.get_market_fundamental_by_date("20210104", "20210108", "005930")
print(df.head(2))

In [18]:
# 일자별 거래대금 조회
# input : 시작날짜, 종료날짜, 종목
#   - on: 매수, 매도, 순매수(DEFAULT)
df = stock.get_market_trading_value_by_date("20210115", "20210122", "005930")
df
df.index[0]

Timestamp('2021-01-15 00:00:00')

In [37]:
# 일자별 거래량 조회
# input : 시작날짜, 종료날짜, 종목
#   - on: 매수, 매도, 순매수(DEFAULT)
df = stock.get_market_trading_volume_by_date("20210115", "20210122", "005930")
df

               기관합계    기타법인       개인    외국인합계  전체
날짜
2021-01-15 -5006115  288832  7485785 -2768502   0
2021-01-18   505669  262604   151228  -919501   0
2021-01-19  1139258  -34023 -2044543   939308   0
2021-01-20 -4157919  262408  4917655 -1022144   0
2021-01-21  -712099 -321732  2890389 -1856558   0
2021-01-22 -6384793   56478  9884815 -3556500   0

In [144]:
# 투자자별 거래대금 조회
# input : 시작날짜, 종료날짜, 종목
df = stock.get_market_trading_value_by_investor("20210115", "20210122", "005930")
# print(df)
# print(df.loc['개인', '매수'])
# print(df.loc['개인', '매도'])
# print(df.loc['개인', '순매수'])
df

                   매도              매수            순매수
투자자구분
금융투자    2580964135000   2309054317700  -271909817300
보험       153322228800     44505136200  -108817092600
투신       258073006600    150715203700  -107357802900
사모        65167773900     60862926800    -4304847100
은행         3369626100      4004806100      635180000
기타금융       3477393800      4877166100     1399772300
연기금 등   4242868457300   3442541806900  -800326650400
기관합계    7307242621500   6016561363500 -1290681258000
기타법인     133693205700    178684949600    44991743900
개인      6918846810800   8972911580500  2054064769700
외국인     2891788072484   2077977924484  -813810148000
기타외국인     15364164000     20799056400     5434892400
전체     17266934874484  17266934874484              0

In [7]:
# 투자자별 거래량 조회
# input : 시작날짜, 종료날짜, 종목
df = stock.get_market_trading_volume_by_investor("20210826", "20210826", "005930")
# print(df.loc['기관합계'])
# print(df.loc['기관합계'][0])
# print(df.loc['기관합계'][1])
df

             매도        매수      순매수
투자자구분
금융투자    1842774   1361611  -481163
보험        28340     19501    -8839
투신        71713     39198   -32515
사모        26427     23972    -2455
은행            0      8000     8000
기타금융      26591         0   -26591
연기금 등   7251929   7053998  -197931
기관합계    9247774   8506280  -741494
기타법인      45168    169923   124755
개인      3578936   5480229  1901293
외국인     3788399   2503018 -1285381
기타외국인     11217     12044      827
전체     16671494  16671494        0

In [38]:
# 투자자별 순매수 상위종목 조회
# input : 시작날짜, 종료날짜, 시장(KOSPI/KOSDAQ), 투자자(금융투자/보험/투신/사모/은행/기타금융/연기금/기관합계/기타법인/개인/외국인/기타외국인/전체)
df = stock.get_market_net_purchases_of_equities_by_ticker("20210115", "20210122", "KOSPI", "개인")
df

,종목명,매도거래량,매수거래량,순매수거래량,매도거래대금,매수거래대금,순매수거래대금
티커,,,,,,,
005930,삼성전자,79567418,102852747,23285329,6918846810800,8972911580500,2054064769700
000270,기아차,44440252,49880626,5440374,3861283906400,4377698855000,516414948600
005935,삼성전자우,15849762,20011325,4161563,1207133611400,1528694164400,321560553000
051910,LG화학,709872,921975,212103,700823533000,908593419000,207769886000
096770,SK이노베이션,4848359,5515777,667418,1298854139000,1478890602000,180036463000
...,...,...,...,...,...,...,...
090430,아모레퍼시픽,1623553,1161213,-462340,369035759000,262552157500,-106483601500
035720,카카오,2681319,2404104,-277215,1205582480500,1077562119500,-128020361000
006400,삼성SDI,1544311,1333957,-210354,1156440902000,990487435000,-165953467000
285130,SK케미칼,2555085,2085241,-469844,1010511216500,823227903000,-187283313500
035420,NAVER,4644834,3449785,-1195049,1512026990000,1109562184000,-402464806000

In [39]:
# 종목별 시가총액 조회
# input : 날짜
df = stock.get_market_cap_by_ticker("20200625")
df

            종가             시가총액       거래량          거래대금       상장주식수
티커
005930   51900  309831714345000  18541624  970494909540  5969782550
000660   84300   61370599369500   3397112  287640892200   728002365
207940  815000   53924475000000    163339  133594217000    66165000
035420  269500   44268984952500   1196267  325381436500   164263395
068270  316000   42640845660000    918369  291688043500   134939385
...        ...              ...       ...           ...         ...
001529   30450       2732034900      2426      73806550       89722
238500     481       2252121846     10841       5711160     4682166
208890     999       2148669180       127        115157     2150820
267810    1150       1779050000      1300       1395000     1547000
224020     450       1215000000         2           900     2700000

[2475 rows x 5 columns]

In [40]:
# ETF티커 조회
# input : 날짜
tickers = stock.get_etf_ticker_list("20200717")
print(tickers[:10])

['292340', '159800', '285000', '287300', '287310', '290080', '284980', '287320', '287330', '252400']

In [ ]:
# ETF이름 조회
# input: 티커
tickers = stock.get_etf_ticker_list("20021014")
for ticker in tickers:
  print(stock.get_etf_ticker_name(ticker))

In [43]:
# 일자별 ETF OHLCV 조회
# input : 시작날짜, 종료날짜, 종목
#   - d/m/y
df = stock.get_etf_ohlcv_by_date("20210104", "20210108", "292340")
type(df)
# print(df.head())

pandas.core.frame.DataFrame

In [ ]:
# 종목별 ETF OHLCV 조회
# input : 날짜
df = stock.get_etf_ohlcv_by_ticker("20210325")
df

In [ ]:
from pykrx import stock
from dataclasses import dataclass
import time

@dataclass
class Info:
  close: int = None
  volume_buy: int = None
  volume_sell: int = None
  volume_netbuy: int = None
  amount_buy: int = None
  amount_sell: int = None
  amount_netbuy: int = None
  individual_volume_buy: int = None
  individual_volume_sell: int = None
  individual_volume_netbuy: int = None
  individual_amount_buy: int = None
  individual_amount_sell: int = None
  individual_amount_netbuy: int = None
  foreign_volume_buy: int = None
  foreign_volume_sell: int = None
  foreign_volume_netbuy: int = None
  foreign_amount_buy: int = None
  foreign_amount_sell: int = None
  foreign_amount_netbuy: int = None
  institution_volume_buy: int = None
  institution_volume_sell: int = None
  institution_volume_netbuy: int = None
  institution_amount_buy: int = None
  institution_amount_sell: int = None
  institution_amount_netbuy: int = None
  corporation_volume_buy: int = None
  corporation_volume_sell: int = None
  corporation_volume_netbuy: int = None
  corporation_amount_buy: int = None
  corporation_amount_sell: int = None
  corporation_amount_netbuy: int = None

ticker_name, ticker_info = {}, {}
for ticker in stock.get_market_ticker_list()[:5]:
  name = stock.get_market_ticker_name(ticker)
  ticker_name[ticker] = name
  ticker_info[ticker] = {}

start = "20210825"
end = "20210830"

for ticker in ticker_name:
  df_close = stock.get_market_ohlcv_by_date(start, end, ticker)
  # 날짜(index) : 기관합계 / 기타법인 / 개인 / 외국인합계 / 전체
  df_volume_buy = stock.get_market_trading_volume_by_date(start, end, ticker, on="매수")
  df_volume_sell = stock.get_market_trading_volume_by_date(start, end, ticker, on="매도")
  df_volume_netbuy = stock.get_market_trading_volume_by_date(start, end, ticker, on="순매수")
  time.sleep(1)
  df_amount_buy = stock.get_market_trading_value_by_date(start, end, ticker, on="매수")
  df_amount_sell = stock.get_market_trading_value_by_date(start, end, ticker, on="매도")
  df_amount_netbuy = stock.get_market_trading_value_by_date(start, end, ticker, on="순매수")
  
  for idx in df_close.index:
    date = str(idx).split(' ')[0].replace('-', '')
    ticker_info[ticker][date] = Info()
    ticker_info[ticker][date].close = df_close.loc[idx, "종가"]
    ticker_info[ticker][date].institution_volume_buy, ticker_info[ticker][date].corporation_volume_buy, ticker_info[ticker][date].individual_volume_buy, ticker_info[ticker][date].foreign_volume_buy, ticker_info[ticker][date].volume_buy = df_volume_buy.loc[idx] 
    ticker_info[ticker][date].institution_volume_sell, ticker_info[ticker][date].corporation_volume_sell, ticker_info[ticker][date].individual_volume_sell, ticker_info[ticker][date].foreign_volume_sell, ticker_info[ticker][date].volume_sell = df_volume_sell.loc[idx] 
    ticker_info[ticker][date].institution_volume_netbuy, ticker_info[ticker][date].corporation_volume_netbuy, ticker_info[ticker][date].individual_volume_netbuy, ticker_info[ticker][date].foreign_volume_netbuy, ticker_info[ticker][date].volume_netbuy = df_volume_netbuy.loc[idx] 

    ticker_info[ticker][date].institution_amount_buy, ticker_info[ticker][date].corporation_amount_buy, ticker_info[ticker][date].individual_amount_buy, ticker_info[ticker][date].foreign_amount_buy, ticker_info[ticker][date].amount_buy = df_amount_buy.loc[idx] 
    ticker_info[ticker][date].institution_amount_sell, ticker_info[ticker][date].corporation_amount_sell, ticker_info[ticker][date].individual_amount_sell, ticker_info[ticker][date].foreign_amount_sell, ticker_info[ticker][date].amount_sell = df_amount_sell.loc[idx] 
    ticker_info[ticker][date].institution_amount_netbuy, ticker_info[ticker][date].corporation_amount_netbuy, ticker_info[ticker][date].individual_amount_netbuy, ticker_info[ticker][date].foreign_amount_netbuy, ticker_info[ticker][date].amount_netbuy = df_amount_netbuy.loc[idx] 

  # for idx in df.index:
  #   time.sleep(1)
  #   date = str(idx).split(' ')[0].replace('-', '')
  #   ticker_info[ticker][date] = Info()
  #   ticker_info[ticker][date].close = df.loc[idx, "종가"]
  #   ticker_info[ticker][date].institution
  #   df_buy.loc[idx]

  #   df_volume = stock.get_market_trading_volume_by_investor(date, date, ticker)    
  #   individual_volume = df_volume.loc['개인']
  #   foreign_volume = df_volume.loc['외국인']
  #   pension_volume = df_volume.loc['연기금 등']
  #   institutation_volume = df_volume.loc['기관합계'] - pension_volume
  #   volume = df_volume.loc['전체']
  #   ticker_info[ticker][date].pension_volume_sell, ticker_info[ticker][date].pension_volume_buy, ticker_info[ticker][date].pension_volume_netbuy = pension_volume
  #   ticker_info[ticker][date].institutation_volume_sell, ticker_info[ticker][date].institutation_volume_buy, ticker_info[ticker][date].institutation_volume_netbuy = institutation_volume
  #   ticker_info[ticker][date].individual_volume_sell, ticker_info[ticker][date].individual_volume_buy, ticker_info[ticker][date].individual_volume_netbuy = individual_volume
  #   ticker_info[ticker][date].foreign_volume_sell, ticker_info[ticker][date].foreign_volume_buy, ticker_info[ticker][date].foreign_volume_netbuy = foreign_volume
  #   ticker_info[ticker][date].volume_sell, ticker_info[ticker][date].volume_buy, ticker_info[ticker][date].volume_netbuy = volume

  #   df_amount = stock.get_market_trading_value_by_investor(date, date, ticker)   
  #   individual_amount = df_amount.loc['개인']
  #   foreign_amount = df_amount.loc['외국인']
  #   pension_amount = df_amount.loc['연기금 등']
  #   institutation_amount = df_amount.loc['기관합계'] - pension_amount
  #   amount = df_amount.loc['전체']
  #   ticker_info[ticker][date].pension_amount_sell, ticker_info[ticker][date].pension_amount_buy, ticker_info[ticker][date].pension_amount_netbuy = pension_amount
  #   ticker_info[ticker][date].institutation_amount_sell, ticker_info[ticker][date].institutation_amount_buy, ticker_info[ticker][date].institutation_amount_netbuy = institutation_amount
  #   ticker_info[ticker][date].individual_amount_sell, ticker_info[ticker][date].individual_amount_buy, ticker_info[ticker][date].individual_amount_netbuy = individual_amount
  #   ticker_info[ticker][date].foreign_amount_sell, ticker_info[ticker][date].foreign_amount_buy, ticker_info[ticker][date].foreign_amount_netbuy = foreign_amount
  #   ticker_info[ticker][date].amount_sell, ticker_info[ticker][date].amount_buy, ticker_info[ticker][date].amount_netbuy, = amount

ticker_info

In [43]:
# 일자별 ETF OHLCV 조회
# input : 시작날짜, 종료날짜, 종목
#   - d/m/y
df = stock.get_etf_ohlcv_by_date("20210104", "20210108", "292340")
print(df.head())

pandas.core.frame.DataFrame

In [1]:
from pykrx import stock
import pandas as pd
import time
import os
from openpyxl import load_workbook

try:
  ticker_name, ticker_info = {}, {}
  # for ticker in stock.get_market_ticker_list()[:10]:
  for ticker in stock.get_market_ticker_list()[:5]:
    name = stock.get_market_ticker_name(ticker)
    ticker_name[ticker] = name
  # for ticker in stock.get_market_ticker_list(market='KOSDAQ'):
    # name = stock.get_market_ticker_name(ticker)
    # ticker_name[ticker] = name

  start = "20210330"
  end = "20210902"

  for ticker in ticker_name:
    try:
      df = stock.get_market_ohlcv_by_date(start, end, ticker)
      # 날짜(index) : 기관합계 / 기타법인 / 개인 / 외국인합계 / 전체
      # df_volume_buy = stock.get_market_trading_volume_by_date(start, end, ticker, on="매수").rename(columns={'기관합계':'기관합계(거래량)-매수', '기타법인':'기타법인(거래량)-매수', '개인':'개인(거래량)-매수', '외국인합계':'외국인합계(거래량)-매수', '전체':'전체(거래량)-매수'})
      # df_volume_sell = stock.get_market_trading_volume_by_date(start, end, ticker, on="매도").rename(columns={'기관합계':'기관합계(거래량)-매도', '기타법인':'기타법인(거래량)-매도', '개인':'개인(거래량)-매도', '외국인합계':'외국인합계(거래량)-매도', '전체':'전체(거래량)-매도'})
      df_volume_netbuy = stock.get_market_trading_volume_by_date(start, end, ticker, on="순매수").rename(columns={'기관합계':'기관합계(거래량)-순매수', '기타법인':'기타법인(거래량)-순매수', '개인':'개인(거래량)-순매수', '외국인합계':'외국인합계(거래량)-순매수', '전체':'전체(거래량)-순매수'})
      time.sleep(1)
      # df_amount_buy = stock.get_market_trading_value_by_date(start, end, ticker, on="매수").rename(columns={'기관합계':'기관합계(거래대금)-매수', '기타법인':'기타법인(거래대금)-매수', '개인':'개인(거래대금)-매수', '외국인합계':'외국인합계(거래대금)-매수', '전체':'전체(거래대금)-매수'})
      # df_amount_sell = stock.get_market_trading_value_by_date(start, end, ticker, on="매도").rename(columns={'기관합계':'기관합계(거래대금)-매도', '기타법인':'기타법인(거래대금)-매도', '개인':'개인(거래대금)-매도', '외국인합계':'외국인합계(거래대금)-매도', '전체':'전체(거래대금)-매도'})
      df_amount_netbuy = stock.get_market_trading_value_by_date(start, end, ticker, on="순매수").rename(columns={'기관합계':'기관합계(거래대금)-순매수', '기타법인':'기타법인(거래대금)-순매수', '개인':'개인(거래대금)-순매수', '외국인합계':'외국인합계(거래대금)-순매수', '전체':'전체(거래대금)-순매수'})
      # df_foreign = stock.get_exhaustion_rates_of_foreign_investment_by_date(start, end, ticker)

      df_total = pd.concat([df, df_volume_netbuy, df_amount_netbuy], axis = 1, join='inner')
      df_total.insert(0, '티커', str(ticker))
      df_total.insert(1, '종목이름', ticker_name[ticker])
      ticker_info[ticker] = df_total

      if not os.path.exists('test.csv'):
        ticker_info[ticker].to_csv('test.csv', sep=',', mode='w', encoding='utf-8-sig')
      else:
        ticker_info[ticker].to_csv('test.csv', sep=',', mode='a', encoding='utf-8-sig', header=False)
    except:
      pass
except Exception as ex:
  print(ex)

In [32]:
from sqlalchemy import create_engine
import pymysql
import pandas as pd
from pykrx import stock
import time
import os
from openpyxl import load_workbook

try:
  ticker_name = {}
  for ticker in stock.get_market_ticker_list():
    name = stock.get_market_ticker_name(ticker)
    ticker_name[ticker] = name
  for ticker in stock.get_market_ticker_list(market='KOSDAQ'):
    name = stock.get_market_ticker_name(ticker)
    ticker_name[ticker] = name

  start = "20210101"
  end = "20210902"

  for ticker in ticker_name:
    try:
      df = stock.get_market_ohlcv_by_date(start, end, ticker).drop(['시가', '고가', '저가'], axis=1).rename(columns={'종가':'close', '거래량':'volume'})
      df.index.names = ['date']
      df_volume_netbuy = stock.get_market_trading_volume_by_date(start, end, ticker, on="순매수").rename(columns={'기관합계':'insVol', '기타법인':'etcVol', '개인':'indVol', '외국인합계':'forVol'}).drop(['전체'], axis=1)
      df_amount_netbuy = stock.get_market_trading_value_by_date(start, end, ticker, on="순매수").rename(columns={'기관합계':'insAmt', '기타법인':'etcAmt', '개인':'indAmt', '외국인합계':'forAmt'}).drop(['전체'], axis=1)
      df_total = pd.concat([df, df_volume_netbuy, df_amount_netbuy], axis = 1, join='inner')
      df_total.insert(0, 'ticker', str(ticker))
      df_total.insert(1, 'name', ticker_name[ticker])

      db_connection = create_engine('mysql+pymysql://root:root@192.168.56.100:3306/INDEX_DUCK', encoding='utf-8')
      conn = db_connection.connect()

      df_total.to_sql(name='stocks', con=db_connection, if_exists='append', index=True, index_label="date")

      conn.close()
      time.sleep(1)
    except Exception as e:
      print(e)
      pass
except Exception as ex:
  print(ex)

Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements
Length mismatch: Expected axis has 0 elements, new values have 6 elements

In [ ]:
import pymysql

db = pymysql.connect(host='192.168.56.100', port=3306, user='root', passwd='root', db='INDEX_DUCK', charset='utf8')
cursor = db.cursor()
try:
  getTickersSql = """
    SELECT DISTINCT ticker FROM stocks
  """
  cursor.execute(getTickersSql)
  tickers = list(cursor.fetchall())

  for ticker in tickers:
    print(ticker[0])
    getTickerInfoSql = """
      SELECT *
      FROM stocks
      WHERE ticker = '%s'
    """ % (ticker[0])

    cursor.execute(getTickerInfoSql)
    tickerInfos = list(map(list, cursor.fetchall()))
    tickerInfos[0] += [tickerInfos[0][i] for i in range(5, 13)]
    for idx in range(1, len(tickerInfos)):
      befInfo = tickerInfos[idx - 1]
      info = tickerInfos[idx]
      tmpCum = [a + b for a, b in zip(befInfo[13:], info[5:])]
      tickerInfos[idx] += tmpCum
    try:
      updateInfoSql = """
        INSERT INTO last_12m(date, ticker, name, close, volume, insVol, etcVol, indVol, forVol, insAmt, etcAmt, indAmt, forAmt, insVolCum, etcVolCum, indVolCum, forVolCum, insAmtCum, etcAmtCum, indAmtCum, forAmtCum)
        VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
      """
      updateInfoVal = tickerInfos
      cursor.executemany(updateInfoSql, updateInfoVal)
      db.commit()
    except Exception as ex1:
      print(ex1)
      pass
except Exception as ex2:
  print(ex2)
  pass

db.close()